### ISSUE TITLE
Epic games

### ISSUE THREAD

**Issue by NEXUSBeam1812** [ottomated/CrewLink#638]
# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [ ] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [ ] I have checked that someone else has not suggested this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)
3. [ ] My feature request is not one of the **commonly suggested features**:
- Adjustable voice radius
- Mobile support
- Linux / MacOS support
- Itch.io support

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I want to be able to use poximity chat with the epic games version of Among Us.
**Describe alternatives you've considered**

**Additional context**

**Comment by MatadorProBr** [comment]
Do not create another issue as already have 12 issues on the same subject, this is caused because of the new update of Among Us that ended up breaking the CrewLink and have to wait for Ottomated to solve this problem but have a solution for this, look the issue in [#623](https://github.com/ottomated/CrewLink/issues/623#issuecomment-793888862) that solves this problem.
